// Generated by CoffeeScript 1.8.0

/*
BLOCK COMMENT -- probably a license
 */
var Dummy;

module.exports = Dummy = (function() {
  function Dummy() {}

  Dummy.prototype.thing = function() {
    return "other thing";
  };

  return Dummy;

})();
