// Generated by CoffeeScript 1.9.0

/*
Testing license injection
 */
var Dummy;

module.exports = Dummy = (function() {
  function Dummy() {}

  Dummy.prototype.thing = function() {
    return "other thing";
  };

  Dummy.prototype.whoops = function() {
    return "dhh";
  };

  Dummy.prototype["else"] = function() {
    return "ok";
  };

  return Dummy;

})();
